apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
type: Opaque
stringData:
  MYSQL_USER: "nextcloud"
  MYSQL_ROOT_PASSWORD: "mysecretpassword"
  MYSQL_PASSWORD: "nextcloudpassword"
  MYSQL_DATABASE: "nextcloud"
