apiVersion: v1
kind: Pod
metadata:
  name: blocked-pod
  namespace: my-secure-namespace
spec:
  containers:
    - name: privileged-container
      image: alpine:latest
      securityContext:
        privileged: true # Privilegierter Container
