apiVersion: v1
kind: Pod
metadata:
  name: warning-pod
  namespace: my-secure-namespace
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        runAsUser: 0 # Als root-Benutzer laufen
        allowPrivilegeEscalation: false
