apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
spec:
  volumes:
    - name: shared
      emptyDir: {}
  containers:
    - name: c1
      image: alpine:3.12.0
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: shared
          mountPath: /etc/a
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
    - name: c2
      image: alpine:3.12.0
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: shared
          mountPath: /etc/b
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
