apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud-data`) }}"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: "{{ .Values.nextcloud.dataStorage }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud-config`) }}"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: "{{ .Values.nextcloud.configStorage }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud`) }}"
  labels:
    app: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud`) }}"
spec:
  type: ClusterIP
  selector:
    app: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud`) }}"
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud`) }}"
  labels:
    app: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud`) }}"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud`) }}"
  template:
    metadata:
      labels:
        app: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud`) }}"
    spec:
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud-data`) }}"
        - name: nextcloud-config
          persistentVolumeClaim:
            claimName: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud-config`) }}"
      containers:
        - name: nextcloud
          image: "{{ .Values.nextcloud.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          env:
            - name: MYSQL_HOST
              value: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `db-clusterip`) }}"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `db-app`) }}"
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `db-app`) }}"
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `db-app`) }}"
                  key: MYSQL_PASSWORD
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "{{ .Values.nextcloud.trustedDomains }}"
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html/data
            - name: nextcloud-config
              mountPath: /var/www/html/config
          resources:
            requests:
              cpu: "{{ .Values.nextcloud.resources.requests.cpu }}"
              memory: "{{ .Values.nextcloud.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.nextcloud.resources.limits.cpu }}"
              memory: "{{ .Values.nextcloud.resources.limits.memory }}"
          readinessProbe:
            httpGet:
              path: /status.php
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /status.php
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 10
