apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `db-pdb`) }}"
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `db`) }}"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud-pdb`) }}"
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `nextcloud`) }}"
