apiVersion: v1
kind: Secret
metadata:
  name: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `db-app`) }}"
  labels:
    app: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `db`) }}"
type: Opaque
stringData:
  MYSQL_DATABASE: {{ .Values.database.dbName | quote }}
  MYSQL_USER: {{ .Values.database.user | quote }}
  MYSQL_PASSWORD: {{ .Values.database.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `db-root`) }}"
  labels:
    app: "{{ include `nextcloud-chart.fullname` (dict `root` . `name` `db`) }}"
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | quote }}
