apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-db-app"
  labels:
    app: "{{ .Release.Name }}-db"
type: Opaque
stringData:
  MYSQL_DATABASE: {{ .Values.database.dbName | quote }}
  MYSQL_USER: {{ .Values.database.user | quote }}
  MYSQL_PASSWORD: {{ .Values.database.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-db-root"
  labels:
    app: "{{ .Release.Name }}-db"
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | quote }}
